FROM debian:wheezy

MAINTAINER Jean-Baptiste BARTH <jeanbaptiste.barth@gmail.com>

ENV DEBIAN_FRONTEND noninteractive

#prerequisites
RUN apt-get update # 2013-06-11

#bind
RUN apt-get install -y bind9
